name: Preview Deployment
on:
  pull_request_target:

jobs:
  deploy-preview:
    environment: Preview
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      deployments: write

    name: Deploy Preview

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Build site
        run: pnpm install && pnpm build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1

        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: site-preview
          directory: build
          deploymentName: Preview
